server:
  port: 9010

spring:
  application:
    name: MavenProject_Base
  rabbitmq:
    host: 39.93.160.110

aliyun:
  sms:
    accessKeyId : LTAILeEkYHKWhrPt
    accessKeySecret :
    templateCode:
    signName: