server:
  port: 10010

spring:
  application:
    name: MavenProject-Config
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:zby123456/Spring-Boot-Config.git
          uri: https://github.com/zby123456/Spring-Boot-Config.git
  rabbitmq:
    host: 39.96.160.110

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
