server:
  port: 9007

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: MavenProject-Comments
  data:
    mongodb:
      host: 39.96.160.110
      database: Project_comment

  redis:
    host: 39.96.160.110





