server:
  port: 9004

spring:
  application:
    name: MavenProject_article
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://cdb-6kot9g5e.cd.tencentcdb.com:10007/project_article?characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://localhost:3306/project_article?characterEncoding=utf-8
    username: root
    password: zby123456


  jpa:
    database-platform:
      # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
      org.hibernate.dialect.MySQL5InnoDBDialect
    database: MySQL
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update




